### PR TITLE
Add support for video messages

### PR DESCRIPTION
**Pull request by odelma**
These changes should enable similar processing to video messages as was previously added for voice messages. The corresponding shell script should be named ~/dtgbot/bash/video_note.sh

### CODE REVIEW

**Comment by jvanderzande** [comment]
Thought I left a comment already but don't see it anymore so second try:
Thanks for the pull request. I tested it after merging and found it contained an error so guess you didn't copy your working version. Fixed it in the commit after the merge. 
Jos

**Comment by odelma** [comment]
Yes, sorry. I had it open in nano editor on an iTerm window from which it is hard to copy the entire script. So I just snipped the changed bits but apparently I wasn't careful enough in doing so. Apologies for the inconvenience, should always take the time and copy the entire working script...:smile:

**Comment by jvanderzande** [comment]
I have the Github checked out to my Win10 computer and have a samba map to the raspberry, so it is easy to use an Editor & WinMerge on my Computer to do easy editing&merging of the sourcefiles on the Raspberry.  ;)

**Comment by odelma** [comment]
Yes, something like that really sounds like the way to go especially if submitting pull requests becomes a habit! 😃

**Pull request merged**
